Read in the necessary imports:

In [24]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from scipy import linalg
from sklearn.preprocessing import StandardScaler

### Linear Algebra Python Intro

1.Let's see what the very important numpy and linalg packages can help us with. We can create matrices and multiply them together:

In [25]:
A = np.matrix([[3,0],[8,-1]])
b = np.matrix([[1],[2]])
A*b

matrix([[3],
        [6]])

2.We can calculate the inverse, tranpose, and the determinant of a matrix:

In [26]:
#inverse:
print(linalg.inv(A))

print()

#transpose:
print(A.T)

print()

#determinant:
print(linalg.det(A))

[[ 3.33333333e-01  6.93889390e-18]
 [ 2.66666667e+00 -1.00000000e+00]]

[[ 3  8]
 [ 0 -1]]

-3.0


3.We can solve the system $Ax=b$:

In [27]:
linalg.solve(A, b)

array([[0.33333333],
       [0.66666667]])

4.We can find the least squares solution and projection:

In [28]:
#least squares
A=np.matrix([[1,1],[1,2],[1,3]])
b=np.matrix([[1],[2],[2]])

X=linalg.inv(A.T*A)*A.T*b
print(X) # solution
print()
print(A*X) # projection

[[0.66666667]
 [0.5       ]]

[[1.16666667]
 [1.66666667]
 [2.16666667]]


5.We can also calculate the eigenvalues and eigenvectors of a matrix, which we'll get to more later:

In [29]:
A=np.matrix([[3,0],[8,-1]])

#eigenvalues:
print(linalg.eigvals(A))

#eigenvalues and eigenvectors:
print(linalg.eig(A))

[-1.+0.j  3.+0.j]
(array([-1.+0.j,  3.+0.j]), array([[0.        , 0.4472136 ],
       [1.        , 0.89442719]]))


Note that the above output is read as $ \lambda_1 = -1, \lambda_2 = 3$ with eigenvectors $v_1 = [0,1],v_2=[0.447,0.894]$, which are the normalized versions of what you get from obtaining $v_1 = [0,1],v_2=[1,2]$ by hand.

I must admit that the output you get from typing ```eigenvectors(([[3,0],[8,-1]])``` into wolfram alpha is nicer.

### College Rankings

1.Read in the US News & World Report 2013 College Rankings:

In [30]:
df = pd.read_csv('data/collegedata.csv')
df

College  Score  Academic Reputation  \
0              williams    100                   92   
1               amherst     98                   92   
2            swarthmore     96                   91   
3            middlebury     94                   87   
4                pomona     94                   87   
5               bowdoin     93                   87   
6             wellesley     93                   89   
7               carlton     92                   88   
8             haverford     91                   83   
9     claremont_mckenna     90                   85   
10               vassar     90                   88   
11             davidson     89                   83   
12          harvey_mudd     89                   89   
13     us_naval_academy     88                   88   
14   washington_and_lee     88                   78   
15             hamilton     87                   81   
16             wesleyan     86                   85   
17                colby     84                   81   
18              colgate     84                   83   
19                smith     84                   85   
20  us_military_academy     83                   83   
21                bates     83                   83   
22             grinnell     83                   86   
23           macalaster     82                   83   
24            bryn_mawr     81                   83   
25              oberlin     81                   82   

    Selectivity rank (lower = better)     SAT  Percent in Top 10 of HS  \
0                                   4  1420.0                       91   
1                                   5  1425.0                       84   
2                                   6  1440.0                       84   
3                                   6  1385.0                       86   
4                                   2  1460.0                       90   
5                                   8  1410.0                       83   
6                                  12  1390.0                       78   
7                                  12  1415.0                       78   
8                                   2  1400.0                       94   
9                                  14  1390.0                       71   
10                                 14  1395.0                       74   
11                                 10  1360.0                       82   
12                                  1  1500.0                       95   
13                                 46  1270.0                       53   
14                                  9  1395.0                       81   
15                                 17  1390.0                       74   
16                                 19  1390.0                       66   
17                                 25  1335.0                       61   
18                                 19  1350.0                       67   
19                                 35  1320.0                       61   
20                                 28  1260.0                       58   
21                                 28  1340.0                       58   
22                                 32     NaN                       62   
23                                 19  1340.0                       70   
24                                 39  1315.0                       60   
25                                 19  1370.0                       68   

    Acceptance Rate  Fac Resources Rank (lower = better)  \
0                17                                    3   
1                13                                    7   
2                15                                    7   
3                18                                   17   
4                14                                   20   
5                16                                   14   
6                31                                   12   
7                31                                

2.Drop Grinnell since it does not contain SAT info:

In [31]:
df = df[df['College'] != 'grinnell']

3.Save the Score column as series b and save the rest of the dataframe (except for the college and score columns) as A_dataframe:

In [32]:
b = df['Score']
A_dataframe = df.drop(columns=['College', 'Score'])

4.Convert the dataframes to numpy matrices and then tranpose vector b so that the shapes are 25x14 and 25x1.

In [33]:
A=np.matrix(A_dataframe)
b=np.matrix(b)
b = b.T
print(A.shape, b.shape)

(25, 14) (25, 1)


5.Apply the least squares transformation:

In [34]:
X=linalg.inv(A.T*A)*(A.T)*b

6.Print the weights in decending order:

In [35]:
categories = A_dataframe.columns                   # column names

tuples = []                                        # create tuples containing the category weights and names
for i in range(len(categories)):
    tuples.append((X[i][0,0], categories[i]))
    
tuples.sort(reverse = True)                        # sort in decending order

for i in range(len(categories)):                   # print the output
    print(tuples[i])

(0.4748330614760352, 'Freshmen Retention')
(0.44402849910595643, 'Academic Reputation')
(0.1568103639574019, 'Alumni Giving rank')
(0.0834561380982426, 'Percent in Top 10 of HS')
(0.06145716039604565, 'Fac Student Ratio (lower = better)')
(0.045818800864619647, 'Selectivity rank (lower = better)')
(0.024414250428624662, 'Percent classes fewer than 20 students')
(0.014115335305337595, 'Percentage classes greater than 50 students (lower = better)')
(-0.002214583741056597, 'SAT')
(-0.022757846448289154, 'Percent full time faculty')
(-0.029479732409627424, 'Acceptance Rate')
(-0.06828671150853616, 'Graduation Retention rank (lower = better)')
(-0.08629494142243521, 'Fac Resources Rank (lower = better)')
(-0.10011751785238254, 'Financial resources rank (lower = better)')


7.What questions or observations do you have about the importance of these categories?

In [36]:
#insert here

8.Print Colby's actual score and predicted score:

In [37]:
#get colby's info
colby = df[df['College'] == 'colby']

#apply the least squares projection to colby's info
colby = colby.drop(columns = ['College', 'Score'])
colby = np.matrix(colby)
colby

projection = colby*X

#print the predicted and actual ranking
print('predicted ranking:', projection[0,0])
print('colby actual ranking:', df[df['College'] == 'colby']['Score'].values)

predicted ranking: 84.55517212864586
colby actual ranking: [84]


The average absolute error is:

In [38]:
error = 0
for i in range(len(A)):
    projection = A[i][:]*X
    newerror = abs(projection[0,0] - b[i,0])
    error = error + newerror
    
print('Average Absolute Prediction Error:', error/len(A))

Average Absolute Prediction Error: 0.49539386508238237


### A Discussion of Scaling

SAT Scores are on a much different scale than the other variables, so perhaps we should scale first? We have several options. We do NOT want to use the Standard scaler in this case because it causes the square matrix  $A^T A$ to have a determinant very close to zero, making it a nearly non-invertible matrix, which is bad.

In [39]:
scaler = StandardScaler()

scaler.fit(A_dataframe)

A = np.matrix(scaler.transform(A_dataframe))

print(linalg.det(linalg.inv(A.T*A)))

5.22950749562984e-14


/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """


We can try using the MinMax scaler instead, and this will no longer give us a zero determinat:

In [40]:
scaler = MinMaxScaler()

scaler.fit(A_dataframe)

A = np.matrix(scaler.transform(A_dataframe))

print(linalg.det(linalg.inv(A.T*A)))

8.073530888128822


/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


However, it still does not give us predictions as good as the non-scaled version. For example, the weightings are wackier and Colby's prediction is worse:

In [41]:
X=linalg.inv(A.T*A)*(A.T)*b

categories = A_dataframe.columns                   # column names

tuples = []                                        # create tuples containing the category weights and names
for i in range(len(categories)):
    tuples.append((X[i][0,0], categories[i]))
    
tuples.sort(reverse = True)                        # sort in decending order

for i in range(len(categories)):                   # print the output
    print(tuples[i])
    
    
#get colby's info
colby = df[df['College'] == 'colby']

#apply the least squares projection to colby's info
colby = colby.drop(columns = ['College', 'Score'])



colby = scaler.transform(colby)   # don't scale because it gives worse results
colby = np.matrix(colby)
colby

projection = colby*X

#print the predicted and actual ranking
print('predicted ranking:', projection[0,0])
print('colby actual ranking:', df[df['College'] == 'colby']['Score'].values)

(90.08714553229467, 'Selectivity rank (lower = better)')
(62.90344262517712, 'Percent in Top 10 of HS')
(28.033586279227876, 'SAT')
(16.834509195267742, 'Academic Reputation')
(16.412458903052826, 'Percent classes fewer than 20 students')
(9.908130978435764, 'Alumni Giving rank')
(8.702879857101745, 'Fac Resources Rank (lower = better)')
(7.902273414080135, 'Fac Student Ratio (lower = better)')
(6.572495288934505, 'Financial resources rank (lower = better)')
(-0.3363738170115411, 'Percent full time faculty')
(-6.436559188506777, 'Acceptance Rate')
(-6.44794516704593, 'Percentage classes greater than 50 students (lower = better)')
(-11.645287688328125, 'Freshmen Retention')
(-23.80914101286759, 'Graduation Retention rank (lower = better)')
predicted ranking: 78.04071482316772
colby actual ranking: [84]


The average error is also worse:

In [42]:
error = 0
for i in range(len(A)):
    projection = A[i][:]*X
    newerror = abs(projection[0,0] - b[i,0])
    error = error + newerror
    
print('Average Absolute Prediction Error:', error/len(A))

Average Absolute Prediction Error: 3.3892794524637186


In summary, when using Ordinary Least Squares to solve for the closed form solution, feature scaling will NOT be necessary; in fact, it may make our predictions worse.

The exception is when you apply regularization (L1/L2 Ridge, Lasso, etc.) Then you should use feature scaling. However, in the above examples, we have not applied any regularization.

In the past, we used feature scaling for gradient descent in order to help the solution converge in a shorter period of time.

Speaking of gradient descent...

### Ordinary Least Squares vs. Gradient Descent

There are two ways to solve for an optimal regression solution. You can solve it via the analytical solution (OLS) or via an iterative algorithm such as gradient descent.

1.**Similarities** between the two methods:

- Both can be applied to linear regression models.
- Both are minimizing the sum of the squared residuals $$\sum_{i=1}^n(y^{(i)}_{\text{predicted}}-y^{(i)}_{\text{actual}})^2$$
- Both work for multivariate problems.

2.**Differences** between the two methods:

OLS directly calculates the solution by solving for the system of equations generated when setting all partial derivatives = 0. The whole process is analytical and generates a closed form solution.

In contrast, gradient descent starts from guessing the local min and proceeds by taking small steps along the direction of the steepest descent. It's numerical and iterative and when the step size is small enough, one expects the updated guess to approach the real local min (converge to the least squared solution). In addition, gradient descent is able to tackle a wider array of problems that are analytically unsolvable.

The OLS closed-form solution may (should) be preferred for “smaller” datasets – if computing (a “costly”) matrix inverse is not a concern. For very large datasets, or datasets where the inverse of $X^T X$ may not exist (the matrix is non-invertible or singular, e.g., in case of perfect multicollinearity), the GD or SGD approaches are to be preferred. Here's a good article going into more detail...

https://sebastianraschka.com/faq/docs/closed-form-vs-gd.html